[exclude]
# Check for the word "initializr
"**/*.java" = "initializr"
"**/*.gradle" = "initializr"
"**/*.yml" = "initializr"
"**/*.properties" = "initializr"
"**/*.groovy" = "initializr"
"**/*.Dockerfile" = "initializr"