integration:
  userServiceUrl: http://mockserver:1080

# INITIALIZR:KAFKA-PRODUCER
spring:
  kafka:
    bootstrap-servers: "kafka:9092"
    properties:
      schema.registry.url: http://schema-registry:8081
      sasl:
        mechanism:
        jaas.config:
      security:
        protocol: PLAINTEXT
# INITIALIZR:KAFKA-PRODUCER