integration:
  userServiceUrl: http://mockserver:1080

# INITIALIZR:KAFKA-PRODUCER
kafka:
  producer:
    bootstrap.servers: "kafka:9092"
    schema.registry.url: http://schema-registry:8081
    sasl.mechanism:
    sasl.jaas.config:
    security.protocol: PLAINTEXT
# INITIALIZR:KAFKA-PRODUCER