integration:
  userServiceUrl: http://mockserver:1080

# INITIALIZR:KAFKA-PRODUCER
spring:
  kafka:
    properties:
      sasl:
        mechanism:
        jaas.config:
      security:
        protocol: PLAINTEXT

kafka:
  bootstrap-servers: "kafka:9092"
  schema-registry-url: http://schema-registry:8081
# INITIALIZR:KAFKA-PRODUCER

logging:
  config: classpath:log-config-system-test.xml