-- INITIALIZR:INITIALIZR-DEMO
-- INITIALIZR:DATABASE
CREATE TABLE Employee
(
    Id         INT PRIMARY KEY IDENTITY NOT NULL,
    First_Name VARCHAR(128)             NOT NULL,
    Last_Name  VARCHAR(128)             NOT NULL
)
-- INITIALIZR:DATABASE
-- INITIALIZR:INITIALIZR-DEMO