name: Deploy to test

on:
  workflow_dispatch:
    inputs:
      version:
        description: Image version
        required: true
        default: latest

env:
  # Set deploy information for the service
  # INITIALIZR:WEB
  web_image_name: protector-initializr-java-web
  web_service_name: protector-initializr-java-web
  # INITIALIZR:WEB
  # INITIALIZR:KAFKA-CONSUMER
  kafka_image_name: protector-initializr-java-async
  kafka_service_name: protector-initializr-java-async
  # INITIALIZR:KAFKA-CONSUMER
  service_name: protector-initializr-java
  version: ${{ github.event.inputs.version }}

jobs:
  deploy_test:
    name: Deploy to test
    runs-on: self-hosted
    steps:
      # INITIALIZR:WEB
      - name: Deploy web to test
        uses: protectorinsurance/swarm-ssh-deployer@v1
        with:
          service-name: ${{ env.web_service_name }}
          image: ghcr.io/protectorinsurance/${{ env.web_image_name }}
          image-tag: ${{ env.version }}
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY_FILENAME }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          hostname: ${{ secrets.TEST_DEPLOY_HOSTNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          ghcr-username: ${{ secrets.PROTECTOR_GITHUB_MACHINE_USER }}
          ghcr-token: ${{ secrets.PROTECTOR_GITHUB_MACHINE_TOKEN }}
      # INITIALIZR:WEB
      # INITIALIZR:KAFKA-CONSUMER
      - name: Deploy async to test
        uses: protectorinsurance/swarm-ssh-deployer@v1
        with:
          service-name: ${{ env.kafka_service_name }}
          image: ghcr.io/protectorinsurance/${{ env.kafka_image_name }}
          image-tag: ${{ env.version }}
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY_FILENAME }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          hostname: ${{ secrets.TEST_DEPLOY_HOSTNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          ghcr-username: ${{ secrets.PROTECTOR_GITHUB_MACHINE_USER }}
          ghcr-token: ${{ secrets.PROTECTOR_GITHUB_MACHINE_TOKEN }}
      # INITIALIZR:KAFKA-CONSUMER