# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & Unit tests
        run: ./gradlew build
      - name: System tests
        run: ./gradlew :web-test:test -PsystemTest --info

  init_script_sanity_checks:
    name: Init script sanity checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests
      - name: Execute python script
        run: python init.py --p "my-awesome-app" --n "no.protector.my.awesome.app" --pf jpa
      - name: Verify that all instances of "initializr" has been removed
        run: |
          grep -q -r --exclude=init.py 'initializr' .
          if [ $? -eq 0 ] ; exit 0 ; exit 1 ; fi

  verify_persistence_framework_options:
    name: Verify persistence framework
    needs: [build, init_script_sanity_checks]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: ['none', 'jdbc', 'jpa']
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests
      - name: Execute python script
        run: python init.py --p "my-awesome-app" --n "no.protector.my.awesome.app" --pf ${{ matrix.run }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Verify that applicaton still builds
        run: gradle clean build -PsystemTest