name: Branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Build & Unit tests
        run: ./gradlew build
      - name: System tests
        run: ./gradlew :web-test:test -PsystemTest --stacktrace

  # INITIALIZR:INITIALIZR-DEMO
  init_script_sanity_checks:
    name: Init script sanity checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests

      - name: Execute python script
        run: python init.py --web "true" --kafka_consumer "true" --p "my-awesome-app" --n "no.protector.my.awesome.app" --clean "false" --pf jpa --kafka_producer "true"

  verify_clean_builds:
    name: Verify builds w/o demo files
    needs: [ build, init_script_sanity_checks ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - web: 'true'
            kafka_consumer: 'false'
            database: 'none'
          - web: 'false'
            kafka_consumer: 'true'
            database: 'jpa'
          - web: 'true'
            kafka_consumer: 'true'
            database: 'jdbc'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests
      - name: Execute python script
        run: python init.py --web "${{ matrix.web }}" --kafka_consumer "${{ matrix.kafka_consumer }}" --p "my-awesome-app" --n "no.protector.my.awesome.app" --clean "true" --pf "${{ matrix.database }}" --kafka_producer "true"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Verify that applicaton still builds
        run: ./gradlew build -PsystemTest --stacktrace

  verify_deployment_variations:
    name: Verify deployment variations
    needs: [ build, init_script_sanity_checks ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - web: 'true'
            kafka_consumer: 'false'
          - web: 'false'
            kafka_consumer: 'true'
          - web: 'true'
            kafka_consumer: 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests
      - name: Execute python script
        run: python init.py --web "${{ matrix.web }}" --kafka_consumer "${{ matrix.kafka_consumer }}" --p "my-awesome-app" --n "no.protector.my.awesome.app" --clean "false" --pf "jdbc" --kafka_producer "true"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: actions/upload-artifact@v2
        with:
          name: source-artifact-${{ matrix.web }}-${{ matrix.kafka_consumer }}
          path: ./
      - name: Do regular build
        run: ./gradlew build --stacktrace
      - name: Run system tests
        run: ./gradlew build -PsystemTest --stacktrace

  verify_persistence_framework_options:
    name: Verify persistence framework variations
    needs: [ build, init_script_sanity_checks ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [ 'none', 'jdbc', 'jpa' ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests
      - name: Execute python script
        run: python init.py --web "true" --kafka_consumer "true" --p "my-awesome-app" --n "no.protector.my.awesome.app" --clean "false" --pf "${{ matrix.database }}" --kafka_producer "true"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Verify that applicaton still builds
        run: ./gradlew build -PsystemTest --stacktrace
# INITIALIZR:INITIALIZR-DEMO