name: Build Main

on:
  push:
    branches:
      - main

env:
  # Set deploy information for the service
  image_name: initializr
  service_name: initializr
  version: ${{ github.run_number }}

jobs:
  build:
    name: Build & Test
    # Use 'self-hosted' if the build requires any internal resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build & Unit tests
        run: ./gradlew build
      - name: System tests
        run: ./gradlew :web-test:test -PsystemTest --info
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            web/build/libs/*
            elasticapm.properties
            Dockerfile

  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          pull: true
          push: true
          tags: |
            ghcr.io/protectorinsurance/${{ env.image_name }}:${{ env.version }}
            ghcr.io/protectorinsurance/${{ env.image_name }}:latest

  deploy_test:
    name: Deploy to test
    if: ${{ false }} # TODO: Delete me when application is set up in ICP
    runs-on: self-hosted
    needs: docker
    steps:
      - name: Deploy to test
        uses: protectorinsurance/swarm-ssh-deployer@v1
        with:
          service-name: ${{ env.service_name }}
          image: ghcr.io/protectorinsurance/${{ env.image_name }}
          image-tag: ${{ env.version }}
          private-key: ${{ secrets.DEPLOY_PRIVATE_KEY_FILENAME }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          hostname: ${{ secrets.TEST_DEPLOY_HOSTNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          ghcr-username: ${{ secrets.PROTECTOR_GITHUB_MACHINE_USER }}
          ghcr-token: ${{ secrets.PROTECTOR_GITHUB_MACHINE_TOKEN }}

  # INITIALIZR:INITIALIZR-DEMO
  init_script_sanity_checks:
    name: Init script sanity checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests

      - name: Execute python script
        run: python init.py --p "my-awesome-app" --n "no.protector.my.awesome.app" --clean "false" --pf jpa --kafka_producer "true"

  verify_persistence_framework_options:
    name: Verify persistence framework
    needs: [ build, init_script_sanity_checks ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - database: 'none'
            clean: 'false'
            kafka: 'true'
            systemTestArgument: -PsystemTest
          - database: 'jdbc'
            clean: 'false'
            kafka: 'true'
            systemTestArgument: -PsystemTest
          - database: 'jpa'
            clean: 'false'
            kafka: 'true'
            systemTestArgument: -PsystemTest
          - database: 'none'
            clean: 'true'
            kafka: 'true'
            systemTestArgument: ''
          - database: 'jdbc'
            clean: 'true'
            kafka: 'true'
            systemTestArgument: ''
          - database: 'jpa'
            clean: 'true'
            kafka: 'true'
            systemTestArgument: ''
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Installing dependencies
        run: pip install requests
      - name: Execute python script
        run: python init.py --p "my-awesome-app" --n "no.protector.my.awesome.app" --clean "${{ matrix.clean }}" --pf "${{ matrix.database }}" --kafka_producer "${{ matrix.kafka }}"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Verify that applicaton still builds
        run: ./gradlew build ${{ matrix.systemTestArgument }}
# INITIALIZR:INITIALIZR-DEMO